### ISSUE TITLE
Zero-shot inference 

### ISSUE THREAD

**Issue by nhussein** [CristianoPatricio/concept-based-interpretability-VLM#2]
Greetings, 
Great work!

Can you kindly explain how to use the weights that you provided for zero shot inference?
Thank you.

**Comment by CristianoPatricio** [comment]
Hello @nhussein,

Thank you for your interest in our work.
Were you able to use the model weights for zero-shot inference?
In any case, I will prepare a python notebook with the necessary steps to perform zero-shot tasks using our pipeline.

**Comment by nhussein** [comment]
I loaded the weights for the trained layers and I passed the results from zero-shot Clip to the layers. However, I did not get the same results as the one in baseline obtained from embeddings.
Thank you for the prompt response, will check out the notebook when it’s up.

**Comment by CristianoPatricio** [comment]
> I loaded the weights for the trained layers and I passed the results from zero-shot Clip to the layers. However, I did not get the same results as the one in baseline obtained from embeddings. Thank you for the prompt response, will check out the notebook when it’s up.

Hi @nhussein,

I've just uploaded the python notebook for zero-shot inference. You can find it [here](https://github.com/CristianoPatricio/concept-based-interpretability-VLM/blob/main/CLIP/scr_zero-shot_inference.ipynb).

In order to reproduce the results of the paper, you should follow the steps described in the [README](https://github.com/CristianoPatricio/concept-based-interpretability-VLM/blob/main/README.md) file.

Thank you.

**Comment by nhussein** [comment]
Thank you!
